name: Hugo-CI
on:
  push:
    branches:
      - develop
    paths-ignore: ".github/**"

jobs:
  job-one:
    name: Deploy
    runs-on: [self-hosted, linux, x64, dev4-pdf-cloud]
    steps:
      - name: hugo build
        run: |
          cd aspose-pdf-cloud-docs && git stash && git pull
          cd lutsk-aspose-prototype && git stash && git pull
          cd themes/lutsk-aspose-theme && git stash && git pull && cd -
          sudo npm install -D --save autoprefixer
          sudo npm install -D --save postcss-cli
